---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "bridge",
                    "name": "br-multus",
                    "bridge": "br-multus0",
                    "capabilities": { "ips": true },
                    "ipam": {
                        "type": "static"
                    }
                } ]
        }'
