---
apiVersion: v1
kind: Pod
metadata:
#  generateName: bridge-
  name: bridge-10.1.1.221
  labels:
    app: multus-bridge
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            {
              "name": "bridge-conf",
              "ips": [ "10.1.1.221/24" ]
            }
    ]'
spec:
  containers:
  - name: centos-tools
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
