---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "ens4",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                }, {
                    "capabilities": { "mac": true },
                    "type": "tuning"
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: macvlan-10.1.1.213
  labels:
    app: multus-macvlan1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf",
              "ips": [ "10.1.1.213/24" ] }
    ]'
spec:
  containers:
  - name: macvlanpod1
    image: docker.io/ubuntu:20.04
    tty: true
---
apiVersion: v1
kind: Pod
metadata:
  name: macvlan-10.1.1.214
  labels:
    app: multus-macvlan2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf",
              "ips": [ "10.1.1.214/24" ] }
    ]'
spec:
  containers:
  - name: macvlanpod2
    image: docker.io/ubuntu:20.04
    tty: true
